import type { OutputFieldDefinition, SearchFieldDefinition } from '../types/material';
import { DEFAULT_WERKS_OPTIONS } from '../types/material';

const MANDT = '100';

export const MOCK_INPUT_FIELDS: SearchFieldDefinition[] = [
  { tableName: 'MARA', fieldName: 'MATNR', hebrewDesc: 'materialSearch.filters.materialNumber', fieldType: 'CHAR', fieldLength: 40, mandt: MANDT },
  { tableName: 'MAKT', fieldName: 'MAKTX', hebrewDesc: 'materialSearch.filters.searchPlaceholder', fieldType: 'CHAR', fieldLength: 40, mandt: MANDT },
  {
    tableName: 'MARA',
    fieldName: 'MTART',
    hebrewDesc: 'materialSearch.filters.materialType',
    fieldType: 'MULTI_SELECT',
    fieldLength: 4,
    mandt: MANDT,
    options: [
      { label: 'materialSearch.enums.materialType.ROH', value: 'ROH' },
      { label: 'materialSearch.enums.materialType.HALB', value: 'HALB' },
      { label: 'materialSearch.enums.materialType.FERT', value: 'FERT' },
      { label: 'materialSearch.enums.materialType.HAWA', value: 'HAWA' },
    ],
  },
  {
    tableName: 'MARA',
    fieldName: 'MBRSH',
    hebrewDesc: 'materialSearch.details.industrySector',
    fieldType: 'MULTI_SELECT',
    fieldLength: 1,
    mandt: MANDT,
    options: [
      { label: 'materialSearch.enums.industrySector.M', value: 'M' },
      { label: 'materialSearch.enums.industrySector.C', value: 'C' },
      { label: 'materialSearch.enums.industrySector.P', value: 'P' },
      { label: 'materialSearch.enums.industrySector.E', value: 'E' },
    ],
  },
  {
    tableName: 'MARA',
    fieldName: 'MEINS',
    hebrewDesc: 'materialSearch.filters.baseUnit',
    fieldType: 'MULTI_SELECT',
    fieldLength: 3,
    mandt: MANDT,
    options: [
      { label: 'PC', value: 'PC' },
      { label: 'KG', value: 'KG' },
      { label: 'L', value: 'L' },
      { label: 'M', value: 'M' },
      { label: 'M2', value: 'M2' },
      { label: 'M3', value: 'M3' },
    ],
  },
  { tableName: 'MARA', fieldName: 'MATKL', hebrewDesc: 'materialSearch.results.columns.materialGroup', fieldType: 'CHAR', fieldLength: 9, mandt: MANDT },
  {
    tableName: 'MARA',
    fieldName: 'SPART',
    hebrewDesc: 'materialSearch.results.columns.division',
    fieldType: 'MULTI_SELECT',
    fieldLength: 2,
    mandt: MANDT,
    options: [
      { label: '00', value: '00' },
      { label: '01', value: '01' },
      { label: '10', value: '10' },
      { label: '20', value: '20' },
    ],
  },
  { tableName: 'MARA', fieldName: 'EAN11', hebrewDesc: 'materialSearch.results.columns.ean', fieldType: 'CHAR', fieldLength: 18, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'WRKST', hebrewDesc: 'materialSearch.results.columns.basicMaterial', fieldType: 'CHAR', fieldLength: 48, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'EXTWG', hebrewDesc: 'materialSearch.results.columns.extMaterialGroup', fieldType: 'CHAR', fieldLength: 18, mandt: MANDT },
  {
    tableName: 'MARA',
    fieldName: 'LABOR',
    hebrewDesc: 'materialSearch.results.columns.labOffice',
    fieldType: 'MULTI_SELECT',
    fieldLength: 3,
    mandt: MANDT,
    options: [
      { label: '001', value: '001' },
      { label: '002', value: '002' },
      { label: 'QA1', value: 'QA1' },
      { label: 'R&D', value: 'R&D' },
    ],
  },
  {
    tableName: 'MARA',
    fieldName: 'XCHPF',
    hebrewDesc: 'materialSearch.results.columns.batchMgmt',
    fieldType: 'BOOLEAN',
    fieldLength: 1,
    mandt: MANDT,
  },
  { tableName: 'MARA', fieldName: 'ERNAM', hebrewDesc: 'materialSearch.details.createdBy', fieldType: 'CHAR', fieldLength: 12, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'AENAM', hebrewDesc: 'materialSearch.details.changedBy', fieldType: 'CHAR', fieldLength: 12, mandt: MANDT },
  {
    tableName: 'MARA',
    fieldName: 'ZZPRIO',
    hebrewDesc: 'materialSearch.results.columns.priority',
    fieldType: 'MULTI_SELECT',
    fieldLength: 1,
    mandt: MANDT,
    options: [
      { label: 'materialSearch.enums.priority.1', value: '1' },
      { label: 'materialSearch.enums.priority.2', value: '2' },
      { label: 'materialSearch.enums.priority.3', value: '3' },
    ],
  },
  { tableName: 'MARA', fieldName: 'ERSDA_START', hebrewDesc: 'materialSearch.filters.startDate', fieldType: 'DATS', fieldLength: 8, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'ERSDA_END', hebrewDesc: 'materialSearch.filters.endDate', fieldType: 'DATS', fieldLength: 8, mandt: MANDT },
  {
    tableName: 'MARC',
    fieldName: 'WERKS',
    hebrewDesc: 'materialSearch.filters.plants',
    fieldType: 'WERKS_SELECTOR',
    fieldLength: 4,
    mandt: MANDT,
    options: DEFAULT_WERKS_OPTIONS,
  },
  { tableName: 'MARC', fieldName: 'ZZSLOC', hebrewDesc: 'materialSearch.results.columns.storageLoc', fieldType: 'CHAR', fieldLength: 4, mandt: MANDT },
];

/** Wide mock column set — exercises horizontal scroll + pinned MATNR. */
export const MOCK_OUTPUT_FIELDS: OutputFieldDefinition[] = [
  { tableName: 'MARA', fieldName: 'MATNR', hebrewDesc: 'materialSearch.results.columns.materialNumber', fieldType: 'CHAR', fieldLength: 40, mandt: MANDT },
  { tableName: 'MAKT', fieldName: 'MAKTX', hebrewDesc: 'materialSearch.results.columns.description', fieldType: 'CHAR', fieldLength: 40, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MTART', hebrewDesc: 'materialSearch.results.columns.materialType', fieldType: 'CHAR', fieldLength: 4, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MBRSH', hebrewDesc: 'materialSearch.details.industrySector', fieldType: 'CHAR', fieldLength: 1, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MEINS', hebrewDesc: 'materialSearch.results.columns.baseUnit', fieldType: 'CHAR', fieldLength: 3, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MATKL', hebrewDesc: 'materialSearch.results.columns.materialGroup', fieldType: 'CHAR', fieldLength: 9, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'SPART', hebrewDesc: 'materialSearch.results.columns.division', fieldType: 'CHAR', fieldLength: 2, mandt: MANDT },
  { tableName: 'MARC', fieldName: 'WERKS', hebrewDesc: 'materialSearch.results.columns.plants', fieldType: 'CHAR', fieldLength: 4, mandt: MANDT },
  { tableName: 'MARC', fieldName: 'WERKS_DISP', hebrewDesc: 'materialSearch.results.columns.plants', fieldType: 'CHAR', fieldLength: 40, mandt: MANDT },
  { tableName: 'MARC', fieldName: 'ZZSLOC', hebrewDesc: 'materialSearch.results.columns.storageLoc', fieldType: 'CHAR', fieldLength: 4, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'EAN11', hebrewDesc: 'materialSearch.results.columns.ean', fieldType: 'CHAR', fieldLength: 18, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'WRKST', hebrewDesc: 'materialSearch.results.columns.basicMaterial', fieldType: 'CHAR', fieldLength: 48, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'EXTWG', hebrewDesc: 'materialSearch.results.columns.extMaterialGroup', fieldType: 'CHAR', fieldLength: 18, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'LABOR', hebrewDesc: 'materialSearch.results.columns.labOffice', fieldType: 'CHAR', fieldLength: 3, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'XCHPF', hebrewDesc: 'materialSearch.results.columns.batchMgmt', fieldType: 'BOOLEAN', fieldLength: 1, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'ZZPRIO', hebrewDesc: 'materialSearch.results.columns.priority', fieldType: 'CHAR', fieldLength: 1, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'BSTME', hebrewDesc: 'materialSearch.results.columns.orderUnit', fieldType: 'CHAR', fieldLength: 3, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'BRGEW', hebrewDesc: 'materialSearch.results.columns.grossWeight', fieldType: 'CHAR', fieldLength: 13, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'NTGEW', hebrewDesc: 'materialSearch.results.columns.netWeight', fieldType: 'CHAR', fieldLength: 13, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'GEWEI', hebrewDesc: 'materialSearch.results.columns.weightUnit', fieldType: 'CHAR', fieldLength: 3, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'VOLUM', hebrewDesc: 'materialSearch.results.columns.volume', fieldType: 'CHAR', fieldLength: 13, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'VOLEH', hebrewDesc: 'materialSearch.results.columns.volumeUnit', fieldType: 'CHAR', fieldLength: 3, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'LAENG', hebrewDesc: 'materialSearch.results.columns.length', fieldType: 'CHAR', fieldLength: 13, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'BREIT', hebrewDesc: 'materialSearch.results.columns.width', fieldType: 'CHAR', fieldLength: 13, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'HOEHE', hebrewDesc: 'materialSearch.results.columns.height', fieldType: 'CHAR', fieldLength: 13, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MEABM', hebrewDesc: 'materialSearch.results.columns.dimUnit', fieldType: 'CHAR', fieldLength: 3, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MHDRZ', hebrewDesc: 'materialSearch.results.columns.minShelfLife', fieldType: 'CHAR', fieldLength: 4, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'MHDHB', hebrewDesc: 'materialSearch.results.columns.totalShelfLife', fieldType: 'CHAR', fieldLength: 4, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'TEMPB', hebrewDesc: 'materialSearch.results.columns.tempCond', fieldType: 'CHAR', fieldLength: 2, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'RAUBE', hebrewDesc: 'materialSearch.results.columns.storageCond', fieldType: 'CHAR', fieldLength: 2, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'BEHVO', hebrewDesc: 'materialSearch.results.columns.containerReq', fieldType: 'CHAR', fieldLength: 2, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'ERSDA', hebrewDesc: 'materialSearch.results.columns.createdOn', fieldType: 'DATS', fieldLength: 8, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'ERNAM', hebrewDesc: 'materialSearch.details.createdBy', fieldType: 'CHAR', fieldLength: 12, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'LAEDA', hebrewDesc: 'materialSearch.details.changedOn', fieldType: 'DATS', fieldLength: 8, mandt: MANDT },
  { tableName: 'MARA', fieldName: 'AENAM', hebrewDesc: 'materialSearch.details.changedBy', fieldType: 'CHAR', fieldLength: 12, mandt: MANDT },
  { tableName: 'STXL', fieldName: 'LONG_TEXT', hebrewDesc: 'materialSearch.details.longDescription', fieldType: 'CHAR', fieldLength: 255, mandt: MANDT },
];
